<a href="https://colab.research.google.com/github/ua-datalab/Workshops/blob/main/Introduction-to-Python-for-Data-Science/Intro_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A very short introduction to Python

### Variable assignment

#### Numbers

When we assign a variable a numeric value, its varibable type is automatically assigned by Python:

In [ ]:
x = 5          # Define x = 5 as an Integer.
print(type(x)) # Prints type "<class 'int'>"
print(x)       # Prints "5"


<class 'int'>
5
6
4
10
25
21
21


We can perform basic arithmetic operations on a numeric variable:

In [ ]:
print(x + 1)   # Addition; prints "6"
print(x - 1)   # Subtraction; prints "4"

In [ ]:
print(x * 2)   # Multiplication; prints "10"
print(x ** 2)  # Exponentiation; prints "25"

Python allows for complex expressions:

In [ ]:
print(x + 1 + 3 * x) # Prints "21". The multiplication operator has precedence over addition.
print((x + 1) + (3 * x)) # Prints "20". The preferred way of writing an operation.

We can change a variable's assigned value by making it save the result of a mathematical operation. Simply add the `=` symbol after the arithmetic operator:

In [ ]:
x = 7
x = x - 1 # replaces the value in variable x with x+1
print(x)

6


In [ ]:
x=7
x -= 1    # Equivalent to "x = x + 1"
print(x)

6


Python assigns the `float` type to a variable if needed:

In [ ]:
y = 5/2   # Automatically defines y = 2.5 as a floating or real number.
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


##### Boolean

We can work with Boolean variables when we need our data in the form of `True` and `False`. This allows us to work with Boolean operators.
Note the capitalization in the use of those keywords:

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


#### Strings

Strings can be used to save alphanumeric input for operations such as concatenation. Python has many methods for working with strings. We can perform text searches, automatically edit text, query a given string, and much more!

See: https://www.w3schools.com/python/python_ref_string.asp

In [ ]:
hello = 'Hello'    # String literals can use single quotes
world = "World!"    # or double quotes; it does not matter.
print(hello)       # Prints "Hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "Hello World!"
print(f'{hello} to the entire {world}')  # prints the values stored in hello and world
                                         # separated by " to the entire "

Hello
5
Hello World!
Hello to the entire World!


In [ ]:
cat = 'cat'
print(cat.capitalize()) #Converts the first character to upper case
print("number of \'c\'s in \'cat\: '", cat.count('c')) #counts number of given substrings in a string

Cat
number of 'c' in 'cat\: ' 1


#### Basic Arithmetic in Python

Integer operators: `+, -, \*, /, //, %`

Floating numbers operators: `+, -, \*, /, \*\*`

Boolean Expressions: `True, False`

Equality (`==`): `5 == 5` returns `True`

Not equal (`!=`): `5 != 5` returns `False`

Greater than (`>`): `5 > 4` returns `True`

Greater or equal than (`>=`): `5 >= 5` returns `True`

Same applies to Less than (`<`) and Less or equal than (`<=`)

Boolean operators `and`, `or`, and `not`: `True and False`, `True or False`, `not True`


In [ ]:
x = 2
y = 7
print(f'Testing if x equals y: {x == y}') #Returns a Boolean value, True if x and y are identical
print("Testing if x does not equal y: ", x != y) #Returns a Boolean value, True if x and y are not identical
print(f'is x greater than y? {y>y}') #Compares x and y

Testing if x equals y: False
Testing if x does not equal y:  True
is x greater than y? False


### Data Types

#### Lists

In [ ]:
# Lists
list1 = [1, 2, 3.0, 4]
list2 = [1., 2, '3', 4]
print(f'List1: {list1}')
print(f'List2 {list2}')
print(f'Combined list {list1+list2}') # Appends list2 at the end of list1

List1: [1, 2, 3.0, 4]
List2 [1.0, 2, '3', 4]
Combined list [1, 2, 3.0, 4, 1.0, 2, '3', 4]


#### Tuples

In [ ]:
tup = 5,                                # tuple created due to trailing comma
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)                              # Create a tuple
print('variable t is: ', type(t))       # Prints "<class 'tuple'>"
print(f'location of t in d: {d[t]}')    # Prints position of tuple t in tuple d, "5"

variable t is:  <class 'tuple'>
location of t in d: 5
1


#### Sets

In [ ]:
list1 = [1, 2, 3.0, 4, 2, 1, 0]
set1 = {0, 1, 2, 3.0, 4} #hardcoded set
set2 = set(list1)        #set created by using a list
print(f'set1: {set1}')
print(f'set2: {set2}')

set1: {0, 1, 2, 3.0, 4}
set2: {0, 1, 2, 3.0, 4}


#### Dictionaries

In [ ]:
d = {'cat': 0, 'dog': 1}      # Create a new dictionary with some data
print(d['cat'])               # Get an entry from a dictionary; prints "cute"
print('cat' in d)             # Check if a dictionary has a given key; prints "True"
d['fish'] = 2                 # Set an entry in a dictionary
print('value of fish: ',\
 {d['fish']})                 # Prints "2"
print('value of monkey: ',\
      d.get('monkey', 'N/A')) # Get an element with a default; prints "N/A"
print('value of fish: ',\
      d.get('fish', 'N/A'))   # Get an element with a default; print actual value if present
del d['fish']                 # Remove an element from a dictionary
print('value of fish: ',\
      d.get('fish', 'N/A'))   # "fish" is no longer a key; prints "N/A"
d.keys()                      # creates an object in datatype dict_keys with all keys in the dictionary
print(f'list of keys: \
    {list(d.keys())}')        #creates a list of keys in the dictionary
print(f'list of values\
    {list(d.values())}')      #creates a list of values in the dictionary

0
True
value of fish:  {2}
value of monkey:  N/A
value of fish:  2
value of fish:  N/A
list of keys:     ['cat', 'dog']
list of values    [0, 1]


### Conditionals


In [ ]:
# Conditional: if, elif, else
x = 3
y = 2
z = 1

if x == y:
     print("Hello")
elif x == z:
     print("Good bye")
else:
     print("Try again")

# Remember: SHIFT+ENTER to run a cell of select the "play button".

Try again


### Loops

In [ ]:
# Loop: for

print("loop 1")
for i in range(5): # default - starts with 0, increases by 1
     print(i)

print("\nloop 2")
for i in range(10, 2, -2): # arguments: start, end, step size
     print(i)

# Loop: while

i = 1
while i < 10:
     print('Next i is = ',i)
     i = i+1 # Next i value is defined


loop 1
0
1
2
3
4

loop 2
10
8
6
4
Next i is =  1
Next i is =  2
Next i is =  3
Next i is =  4
Next i is =  5
Next i is =  6
Next i is =  7
Next i is =  8
Next i is =  9


### Numpy

In [ ]:
# import the numpy library:
import numpy as np

In [ ]:
# Arrays (n-dimensional vectors)

# One dimensional arrays examples
s1 = np.array([1,2,3,4])      # Array of integer numbers
s2 = np.array([1,2,3,4.0])    # Will be converted to floating numbers array, since 4.0 is a float (real)
s3 = np.array([1,2,3,'4'])    # Will be converted to a character array, since '4' is a character
s4 = np.arange(0,5,0.5)       # An array of 0.5 spaced points between 0 and 5, but not including end point 5
s5 = np.linspace(0,5,20)      # Inserts 20 between 0 and 5, includes both end points.
print('s1 is ', s1)
print('s2 is ', s2)
print('s3 is ', s3)
print('s4 is ', s4)

s1 is  [1 2 3 4]
s2 is  [1. 2. 3. 4.]
s3 is  ['1' '2' '3' '4']
s4 is  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
# Adding 2 numeric array makes sense. Since s2 is a float array, the sum s1 + s2 is a float
# or we can scale numeric arrays by multiplying or dividing them by a factor.
print('s1 + s2 = ', s1 + s2)
print('5 * s2 = ', 5*s2)

s1 + s2 =  [2. 4. 6. 8.]
5 * s2 =  [ 5. 10. 15. 20.]


In [ ]:
# How to access the elements of an array
print('s1 = ', s1)
print('Third element of s1, s1[2] = ', s1[2])                           # Obtain the 3rd element of s1... Python starts counting from 0
print('All elements from the second to the fourth s1[1:3] = ', s1[1:3]) # Obtain the second upto before the fourth elements

s1 =  [1 2 3 4]
Third element of s1, s1[2] =  3
All elements from the second to the fourth s1[1:3] =  [2 3]


In [ ]:
# Two and three dimensional arrays
x2 = np.array([[0, 1], [2, 3]])
y3 = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(' x2 = \n', x2, '\n y3 = \n', y3)

 x2 = 
 [[0 1]
 [2 3]] 
 y3 = 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Selecting a row or column of an array
# Remember, Python starts counting from 0.
print('Second column of x2 x2[:,1]\n', x2[:,1]) #prints the second column of x2')
print('Second row of x2: \n', x2[1,:])  # Selects the second row of x2, (here ':'  means 'all columns')
print('First column of y3: \n', y3[:,0]) # Selects the first column of y3 (here ':' means 'all rows')
print('Last element of second row of y3: \n', y3[1,2]) # Selects a specific element on a two dimensional array.

Second column of x2 x2[:,1]
 [1 3]
Second row of x2: 
 [2 3]
First column of y3: 
 [ 4  7 10]
Last element of second row of y3: 
 9


In [ ]:
# Slicing can also be used for arrays similarly as it was used for lists.

# A 2d array with shape (3, 4):
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('original array: \n', a)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print('sliced array b: \n', b)

original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sliced array b: 
 [[2 3]
 [6 7]]


In [ ]:
# Some basic array operations (Only if elements are numbers)
import numpy as np

# Two and three dimensional arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
c = 2

# Print specified values
print('x = ', x)
print('y = ', y)
print('c =', c)

x =  [[1 2]
 [3 4]]
y =  [[5 6]
 [7 8]]
c = 2


In [ ]:
print('Sum x+y = \n', x+y)                                                 # sum
print(' Sum of x + c = \n', x+c)                                           # sum a constant c
print('Division of x/y = \n', x/y)                                         # division
print(' Multiply c*x = \n', c*x)                                           # multiply by a constant c
print('Square of x =', x**2)                                            # Square of a number
print('Array multiplication x @ y = ', x@y)                             # Array multiplication - is a standard matrix multiplication
print('Square root of x =', np.sqrt(x))                                 # Computes the square root of all array elements
print('Exponential of array x = ', np.exp(x))                           # Computes the expo0nential of the array
print('Log of x = ', np.log(x))                                         # Computes the natural logarithm of the array
print('Sum of elements of x = ', np.sum(x))                             # Computes the sum of the elements of the array
print('Computes the arithmetic mean of elements of x = ', np.mean(x))   # Computes the arithmetic mean of the array

Sum x+y = 
 [[ 6  8]
 [10 12]]
 Sum of x + c = 
 [[3 4]
 [5 6]]
Division of x/y = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 Multiply c*x = 
 [[2 4]
 [6 8]]
Square of x = [[ 1  4]
 [ 9 16]]
Array multiplication x @ y =  [[19 22]
 [43 50]]
Square root of x = [[1.         1.41421356]
 [1.73205081 2.        ]]
Exponential of array x =  [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
Log of x =  [[0.         0.69314718]
 [1.09861229 1.38629436]]
Sum of elements of x =  10
Computes the arithmetic mean of elements of x =  2.5


**bold text**### Test your skills

Create a variable called 'num' and assign it the value 12. Print the value of this new variable. Next, print its data type.

In [ ]:
num = <something>
print(<something>)
print('type: ', type(<something>))

Create 3 string variables with the words "meow", "bark" and "chirp. Concatenate these three strings and print:

In [ ]:
x = ""
y = ""
z = ""
concat = <something>
print(concat)

Create a list using the three string variables above, in the same order. Call it "animal_sounds". Print the third element of this new list.

In [ ]:
animal_sounds = something
print(something)

Create a dictionary with three keys, "cat, "dog, and "bird". Assign them values using the three string variables, one variable per key.

In [ ]:
animals = {"cat: something, ..."}

For the array provided below, multiply each element by 20, and subtract the resultant product by 2

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr_multiply = ...
arr_subtract = ...
print(arr_subtract)

[[ 18  38  58]
 [ 78  98 118]]
